version: '3.8'

services:
  rabbitmq1:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq1
    networks:
      - my-network
    ports:
      - "5672:5672"       # AMQP protocol
      - "15672:15672"     # Management UI (for monitoring)
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_LISTENER_TCP_BACKLOG=128  # Increase connection limit
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-setcookie secret_cookie
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins  # Set the plugins file
    volumes:
      - rabbitmq-logs:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins  # Mount the plugins file
    user: root
    healthcheck: 
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  rabbitmq2:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq2
    networks:
      - my-network
    ports:
      - "5673:5672"       # AMQP protocol
      - "15673:15672"     # Management UI (for monitoring)
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_LISTENER_TCP_BACKLOG=128  # Increase connection limit
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-setcookie secret_cookie
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins  # Set the plugins file
      - RABBITMQ_CLUSTER_NODES=rabbit@rabbitmq1
    volumes:
      - rabbitmq-logs:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins  # Mount the plugins file
    user: root
    depends_on:
      - rabbitmq1
    healthcheck: 
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  rabbitmq3:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq3
    networks:
      - my-network
    ports:
      - "5674:5672"       # AMQP protocol
      - "15674:15672"     # Management UI (for monitoring)
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_LISTENER_TCP_BACKLOG=128  # Increase connection limit
      - RABBITMQ_NODENAME=rabbit@rabbitmq3
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-setcookie secret_cookie
      - RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins  # Set the plugins file
      - RABBITMQ_CLUSTER_NODES=rabbit@rabbitmq1
    volumes:
      - rabbitmq-logs:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins  # Mount the plugins file
    user: root
    depends_on:
      - rabbitmq1
    healthcheck: 
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  sender:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: producer
    depends_on:
      rabbitmq1:
        condition: service_healthy  # Wait for RabbitMQ to be ready
    networks:
      - my-network
    ports:
      - "6000:5000"  # Flask app exposed on port 6000
    environment:
      - RABBITMQ_HOST=rabbitmq1
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
    volumes:
      - sender-app:/app
    restart: always

  finance_consumer:
    build:
      context: .
      dockerfile: consumers/Finance/Dockerfile
    container_name: finance_consumer
    depends_on:
      rabbitmq1:
        condition: service_healthy
    networks:
      - my-network
    environment:
      - RABBITMQ_HOST=rabbitmq1
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - QUEUE_NAME=finance_queue  # Finance queue binding
    volumes:
      - finance-app:/app
    restart: always

  hr_consumer:
    build:
      context: .
      dockerfile: consumers/Hr/Dockerfile
    container_name: hr_consumer
    depends_on:
      rabbitmq1:
        condition: service_healthy
    networks:
      - my-network
    environment:
      - RABBITMQ_HOST=rabbitmq1
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - QUEUE_NAME=hr_queue  # HR queue binding
    volumes:
      - hr-app:/app
    restart: always
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - my-network
    ports:
      - "9100:9100"
    restart: unless-stopped
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - my-network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - my-network
    ports:
      - "8081:8080"  # cAdvisor UI
    volumes:
      - cadvisor-logs:/var/run/docker.sock:ro
      - cadvisor-logs:/var/lib/docker:ro
      - cadvisor-logs:/var/log/cadvisor
    restart: unless-stopped

networks:
  my-network:
    driver: bridge

volumes:
  rabbitmq-logs:
  sender-app:
  finance-app:
  hr-app:
  cadvisor-logs:
  cadvisor-data:
