global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:29092']
  
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000'] 

  - job_name: 'consumer_payroll'
    static_configs:
      - targets: ['consumer_payroll:8001']  

  - job_name: 'consumer_security'
    static_configs:
      - targets: ['consumer_security:8002'] 